//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesProjectMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rating
    {
        public int custId { get; set; }
        public int movieId { get; set; }
        public int rating1 { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual movie movie { get; set; }
    }
}
